package org.subsurface;

public class DcException extends Exception {
        // Autogenerated by Eclipse.
        private static final long serialVersionUID = -8966163928310952959L;

        public DcException(int msg) {
                super(String.valueOf(msg));
        }
}
