package org.libdivecomputer;

public class DcException extends Exception {
        // Autogenerated by Eclipse.
        private static final long serialVersionUID = -8966163928310952959L;

        public DcException(String message) {
                super(message);
        }
}
